//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArdeshirV.Forms.Properties {
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class Resources {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		public Resources() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArdeshirV.Forms.Properties.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap ArdeshirV {
			get {
				object obj = ResourceManager.GetObject("ArdeshirV", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap ArdeshirV_Forms_Logo {
			get {
				object obj = ResourceManager.GetObject("ArdeshirV.Forms.Logo", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap Binance {
			get {
				object obj = ResourceManager.GetObject("Binance", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap Bitcoin {
			get {
				object obj = ResourceManager.GetObject("Bitcoin", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap BitcoinCash {
			get {
				object obj = ResourceManager.GetObject("BitcoinCash", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap Cardano {
			get {
				object obj = ResourceManager.GetObject("Cardano", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap Copy {
			get {
				object obj = ResourceManager.GetObject("Copy", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap Dash {
			get {
				object obj = ResourceManager.GetObject("Dash", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap Ethereum {
			get {
				object obj = ResourceManager.GetObject("Ethereum", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap IconError {
			get {
				object obj = ResourceManager.GetObject("IconError", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap IconInfo {
			get {
				object obj = ResourceManager.GetObject("IconInfo", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap IconQuestion {
			get {
				object obj = ResourceManager.GetObject("IconQuestion", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap IconWarning {
			get {
				object obj = ResourceManager.GetObject("IconWarning", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap LGPLv3 {
			get {
				object obj = ResourceManager.GetObject("LGPLv3", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to                    GNU LESSER GENERAL PUBLIC LICENSE
		///                       Version 3, 29 June 2007
		///
		/// Copyright (C) 2007 Free Software Foundation, Inc. &lt;https://fsf.org/&gt;
		/// Everyone is permitted to copy and distribute verbatim copies
		/// of this license document, but changing it is not allowed.
		///
		///
		///  This version of the GNU Lesser General Public License incorporates
		///the terms and conditions of version 3 of the GNU General Public
		///License, supplemented by the additional permissions listed below.
		///
		///  0. A [rest of string was truncated]&quot;;.
		/// </summary>
		public static string LICENSE {
			get {
				return ResourceManager.GetString("LICENSE", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap Litecoin {
			get {
				object obj = ResourceManager.GetObject("Litecoin", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap Monero {
			get {
				object obj = ResourceManager.GetObject("Monero", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap Nano {
			get {
				object obj = ResourceManager.GetObject("Nano", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap NEM {
			get {
				object obj = ResourceManager.GetObject("NEM", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap Neo {
			get {
				object obj = ResourceManager.GetObject("Neo", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap Qtum {
			get {
				object obj = ResourceManager.GetObject("Qtum", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap Question {
			get {
				object obj = ResourceManager.GetObject("Question", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap Ripple {
			get {
				object obj = ResourceManager.GetObject("Ripple", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap Save_Picture {
			get {
				object obj = ResourceManager.GetObject("Save Picture", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap Stellar {
			get {
				object obj = ResourceManager.GetObject("Stellar", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap Tron {
			get {
				object obj = ResourceManager.GetObject("Tron", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap TrueUSD {
			get {
				object obj = ResourceManager.GetObject("TrueUSD", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap USDTether {
			get {
				object obj = ResourceManager.GetObject("USDTether", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap Verge {
			get {
				object obj = ResourceManager.GetObject("Verge", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap ZCash {
			get {
				object obj = ResourceManager.GetObject("ZCash", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	}
}
